### ISSUE TITLE
Fix chat time from UTC to Local

### ISSUE THREAD

**Issue by bobanko** [StepanoidTeam/powerGrid#14]
в чате время неправильное, в UTC

**Comment by fatal10error** [comment]
Not only in chat, EVERYWHERE (in version for example, just need to expect UTC in any endpoint)

**Comment by bobanko** [comment]
server returns this one:
Date: "2017-05-28T22:15:09"
and proper UTC looks like this
Date: "2017-05-28T22:15:09Z"

with Z at the end
